name: Create Module Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create zip file
      run: |
        zip -r module.zip META-INF system module.prop readme.md

    - name: Upload zip file
      uses: actions/upload-artifact@v2
      with:
        name: module
        path: module.zip
