name: Create and Publish Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create zip file
      run: |
        zip -r module.zip META-INF system module.prop readme.md

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: module.zip
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the URL of the created release
      run: echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
